Tweet.create!([
  {title: "カイト", artist: "嵐", writer: "米津玄師", composer: "米津玄師", published: "N", record: "2020/7/29 Release 58th Single「カイト」", online: nil, user_id: 1, image: nil, used: "NHK2020"},
  {title: "RESCUE", artist: "KAT-TUN", writer: "", composer: "", published: "2009", record: "", online: nil, user_id: 1, image: nil, used: nil},
  {title: "Love so sweet :Reborn", artist: "嵐", writer: "", composer: "", published: "", record: "DIGITAL SINGLE「Love so sweet :Reborn」", online: nil, user_id: 1, image: nil, used: ""},
  {title: "Melty Fantasia", artist: "EScape(真壁瑞希, 白石紬, 北沢志保)", writer: "", composer: "", published: "", record: "", online: nil, user_id: 1, image: nil, used: nil},
  {title: "痕跡", artist: "二宮和也", writer: "", composer: "", published: "なし", record: "DVD「2004 嵐！ いざッNow Tour！！」", online: nil, user_id: 1, image: nil, used: ""},
  {title: "INCUBUS", artist: "Acid Black Cherry", writer: "", composer: "林保徳", published: "", record: "Album「L -エル-」", online: nil, user_id: 1, image: nil, used: nil},
  {title: "Anti-Anti（別表記: Unti-Unti）", artist: "櫻井翔", writer: "Rap詞 櫻井翔", composer: "", published: "なし", record: "DVD「2004 嵐！ いざッNow Tour！！」「ARASHI AROUND ASIA Thailand-Taiwan-Korea」「ARASHI AROUND ASIA +in Dome」収録", online: nil, user_id: 1, image: nil, used: ""},
  {title: "ORICross", artist: "AKADRA", writer: "-", composer: "AKADRA", published: "https://soundcloud.com/akadra7800/oricross, https://audius.co/akadra_music/oricross-34296", record: "なし", online: nil, user_id: 1, image: "twitterアイコン.png", used: ""},
  {title: "麒麟の子", artist: "Sexy Zone", writer: "Earsy", composer: "イワツボコーダイ・吹野クワガタ", published: "なし", record: "Sexy Zone 17th Single「麒麟の子/Honey Honey」", online: nil, user_id: 1, image: nil, used: nil},
  {title: "Mazy Night", artist: "King & Prince", writer: "RUCCA", composer: "Tyler Shamy・Tido", published: "なし", record: "2020/6/10 Release 5th Single「Mazy Night」", online: nil, user_id: 1, image: nil, used: "日本テレビ系土曜ドラマ「未満警察 ミッドナイトランナー」主題歌"},
  {title: "ミラクルワンダーマジック", artist: "Hey! Say! JUMP", writer: "2004", composer: "2004", published: "なし", record: "7th Album「PARADE」", online: nil, user_id: 1, image: nil, used: nil},
  {title: "Last Mermaid...", artist: "Hey! Say! JUMP", writer: "", composer: "", published: "なし", record: "Single「Last Mermaid...」", online: nil, user_id: 1, image: nil, used: "家政夫のミタゾノ　主題歌"},
  {title: "君のうた", artist: "嵐", writer: "", composer: "", published: "各配信サイト（Apple Music, Spotify, LINE MUSIC etc...）", record: "2019 Release 56th Single「君のうた」", online: nil, user_id: 1, image: nil, used: "相葉雅紀主演ドラマ「僕としっぽと神楽坂」主題歌"},
  {title: "Decided", artist: "徳川まつり(諏訪彩花) × 馬場このみ(高橋未奈美)", writer: "", composer: "", published: "", record: "「THE IDOLM@STER LIVE THE@TER DREAMERS 03」", online: nil, user_id: 1, image: nil, used: ""},
  {title: "Wake up!", artist: "AAA", writer: "", composer: "", published: "", record: "Single「Wake up!」Best Album「AAA 15th Anniversary All Time Best -Thanx AAA lot-」", online: nil, user_id: 1, image: nil, used: "「ワンピース」オープニングテーマ"},
  {title: "真っ赤なLips", artist: "WANDS", writer: "", composer: "", published: "", record: "", online: nil, user_id: 1, image: nil, used: "「名探偵コナン」オープニングテーマ"},
  {title: "Hello! Wink!", artist: "Poppin'Party", writer: "", composer: "", published: "LINE MUSIC etc", record: "2nd Album「Breakthrough!」", online: nil, user_id: 1, image: nil, used: ""},
  {title: "Dream Land! Dream World!", artist: "A・ZU・NA（上原歩夢, 桜坂しずく, 優木せつ菜）", writer: "", composer: "", published: "", record: "1st Single「Dream Land! Dream World!」", online: nil, user_id: 1, image: nil, used: ""},
  {title: "さくらガール", artist: "NEWS", writer: "", composer: "", published: "", record: "Single「さくらガール」", online: nil, user_id: 1, image: nil, used: ""},
  {title: "KOKORO Magic \"A to Z\"", artist: "Aqours", writer: "畑亜貴", composer: "", published: "", record: "Single「KOKORO Magic \"A to Z\"」", online: nil, user_id: 1, image: nil, used: ""},
  {title: "全く身にならない日々", artist: "キヨ×レトルト", writer: "まふまふ", composer: "まふまふ", published: "Youtube", record: "なし", online: nil, user_id: 1, image: nil, used: "なし"},
  {title: "Love∞Destiny", artist: "Masque:rade（北条加蓮, 佐久間まゆ, 小日向美穂, 緒方智絵里, 多田李衣菜）", writer: "磯谷佳江", composer: "BNSI（kyo）", published: "", record: "「THE IDOLM@STER CINDERELLA GIRLS STARLIGHT MASTER 06 Love∞Destiny」", online: nil, user_id: 1, image: nil, used: ""},
  {title: "-HEROIC ADVENT-", artist: "Roselia", writer: "", composer: "", published: "", record: "3rd Single「熱色スターマイン」, 1st Album「Anfang」", online: nil, user_id: 1, image: nil, used: ""},
  {title: "サイレントマジョリティー", artist: "欅坂46", writer: "", composer: "", published: "", record: "Single「サイレントマジョリティー」, Album「真っ白なものは汚したくなる」", online: nil, user_id: 1, image: nil, used: ""},
  {title: "不協和音", artist: "欅坂46", writer: "", composer: "", published: "", record: "Single「不協和音」, Album「真っ白なものは汚したくなる」", online: nil, user_id: 1, image: nil, used: ""},
  {title: "ラビットファー", artist: "Xs（萩原雪歩, 菊地真, 星井美希, 水瀬伊織）", writer: "", composer: "", published: "", record: "「THE IDOLM@STER MILLION THE@TER WAVE 03」", online: nil, user_id: 1, image: nil, used: ""},
  {title: "ファンファーレ！", artist: "Hey! Say! JUMP", writer: "", composer: "", published: "", record: "Single「ファンファーレ！」", online: nil, user_id: 1, image: nil, used: ""},
  {title: "Be The One", artist: "PANDORA Feat. Beverly", writer: "", composer: "", published: "", record: "Single「Be The One」", online: nil, user_id: 1, image: nil, used: "犬飼貴丈主演特撮ドラマ「仮面ライダービルド」　主題歌"},
  {title: "Jane Doe", artist: "高橋みなみ", writer: "", composer: "", published: "", record: "Single「Jane Doe」", online: nil, user_id: 1, image: nil, used: ""},
  {title: "ORI・GAMI☆ADVENTURE！！", artist: "AKADRA", writer: "", composer: "", published: "https://soundcloud.com/akadra7800/origamiadventure", record: "", online: nil, user_id: 1, image: nil, used: ""},
  {title: "Believe again", artist: "Saint Snow", writer: "", composer: "", published: "", record: "Single「Believe again/Brightest Melody/Over The Next Rainbow」", online: nil, user_id: 1, image: nil, used: "映画「ラブライブ！サンシャイン!!The School Idol Movie Over the Rainbow」挿入歌"},
  {title: "STEP by STEP UP↑↑↑↑", artist: "fourfolium（涼風青葉, 滝本ひふみ, 飯島ゆん, 篠田はじめ）", writer: "", composer: "", published: "", record: "", online: nil, user_id: 1, image: nil, used: "アニメ「NEW GAME!!」オープニングテーマ"},
  {title: "N.M.P. (NO MORE PAIN)", artist: "KAT-TUN", writer: "", composer: "", published: "", record: "Album「NO MORE PAIИ」", online: nil, user_id: 1, image: nil, used: ""},
  {title: "気まぐれメルシィ", artist: "八王子P feat.初音ミク", writer: "", composer: "", published: "", record: "Best Album「Eight -THE BEST OF 八王子P-」", online: nil, user_id: 1, image: nil, used: ""},
  {title: "B Who I Want 2 B", artist: "安室奈美恵 feat. HATSUNE MIKU", writer: "", composer: "", published: "Spotify", record: "Album「_genic」", online: nil, user_id: 1, image: nil, used: ""},
  {title: "ray", artist: "BUMP OF CHICKEN feat. HATSUNE MIKU", writer: "", composer: "", published: "Spotify, Play Music", record: "DIGITAL SINGLE「ray」", online: nil, user_id: 1, image: nil, used: ""},
  {title: "Daylight", artist: "嵐", writer: "", composer: "", published: "各配信サイト（Apple Music, Spotify, LINE MUSIC etc...）", record: "2016 Release Single「I seek / Daylight」, Album「Are You Happy?」, Best Album「5×20 All the BEST!! 1999-2019」", online: nil, user_id: 1, image: nil, used: "松本潤主演ドラマ「99.9 -刑事専門弁護士-」主題歌"},
  {title: "BRAVE JEWEL", artist: "Roselia", writer: "", composer: "", published: "", record: "Single「BRAVE JEWEL」, Album「Wahl」", online: nil, user_id: 1, image: nil, used: "アニメ「Bang Dream！2nd Season」オープニングテーマ"},
  {title: "supersonic", artist: "嵐", writer: "", composer: "", published: "なし", record: "Single「I seek / Daylight」通常盤のみ", online: nil, user_id: 1, image: nil, used: ""},
  {title: "「生きろ」", artist: "NEWS", writer: "", composer: "", published: "なし", record: "", online: nil, user_id: 1, image: nil, used: ""},
  {title: "Monster", artist: "嵐", writer: "", composer: "", published: "各配信サイト（Apple Music, Spotify, LINE MUSIC etc...）", record: "", online: nil, user_id: 1, image: nil, used: "ドラマ「怪物くん」主題歌"},
  {title: "猫中毒", artist: "テゴマス", writer: "", composer: "", published: "なし", record: "Single「猫中毒」", online: nil, user_id: 1, image: nil, used: ""},
  {title: "青いベンチ", artist: "テゴマス", writer: "", composer: "", published: "なし", record: "Single「青いベンチ」、Album「テゴマスのまほう」", online: nil, user_id: 1, image: nil, used: "テレビ朝日系「お願い!ランキング」2月度エンディング･テーマ"},
  {title: "Fake it", artist: "嵐", writer: "", composer: "", published: "なし", record: "Single「君のうた」通常盤", online: nil, user_id: 1, image: nil, used: ""},
  {title: "Sky Again", artist: "嵐", writer: "", composer: "", published: "なし", record: "Single「君のうた」通常盤", online: nil, user_id: 1, image: nil, used: "JAL「Fly for it!」CMソング"},
  {title: "and I'm home", artist: "美樹さやか(喜多村英梨) & 佐倉杏子(野中藍)", writer: "wowaka", composer: "wowaka", published: "", record: "サウンドトラック「魔法少女まどか☆マギカ MUSIC COLLECTION」, Best Album「魔法少女まどか☆マギカ Ultimate Best」", online: nil, user_id: 1, image: nil, used: "TVアニメ「魔法少女まどか☆マギカ」BD/DVD版第9話エンディングテーマ"},
  {title: "てぃーてぃーてぃーてれって てれてぃてぃてぃ 〜だれのケツ〜", artist: "舞祭組", writer: "なかいさん、宮下工務店", composer: "なかいさん、宮下工務店", published: "なし", record: "Single「てぃーてぃーてぃーてれって てれてぃてぃてぃ 〜だれのケツ〜」, Album「舞祭組の、わっ!」", online: nil, user_id: 1, image: nil, used: " 日本テレビドラマ「平成舞祭組男」オープニングテーマ"},
  {title: "恋はスリル、ショック、サスペンス", artist: "愛内里菜", writer: "", composer: "", published: "", record: "Single「恋はスリル、ショック、サスペンス」, Album「Be Happy」, Best Album「Single Collection」「ALL SINGLES BEST 〜THANX 10th ANNIVERSARY〜」, コンピレーションアルバム「THE BEST OF DETECTIVE CONAN 〜名探偵コナン テーマ曲集〜」", online: nil, user_id: 1, image: nil, used: "「名探偵コナン」オープニングテーマ"},
  {title: "LIFE", artist: "嵐", writer: "", composer: "", published: "各配信サイト（Apple Music, Spotify, LINE MUSIC etc...）", record: "Album「Time」", online: nil, user_id: 1, image: nil, used: "「エイブル」CMソング"},
  {title: "Daylight -デイライト-", artist: "Morfonica", writer: "", composer: "", published: "", record: "Single「Daylight -デイライト-」", online: nil, user_id: 1, image: nil, used: ""},
  {title: "千本桜", artist: "黒うさP feat. 初音ミク", writer: "", composer: "", published: "https://www.youtube.com/watch?v=shs0rAiwsGQ", record: "Best Album「黒うさP feat. 初音ミク/5th ANNIVERSARY BEST」", online: nil, user_id: 1, image: nil, used: ""},
  {title: "Summer Madness", artist: "三代目 J Soul Brothers from EXILE TRIBE Feat. Afrojack", writer: "", composer: "", published: "", record: "Single「Summer Madness」, Album「THE JSB LEGACY」", online: nil, user_id: 1, image: nil, used: ""},
  {title: "Entertainment", artist: "Hey! Say! JUMP", writer: "", composer: "", published: "", record: "Single「Lucky-Unlucky / Oh! my darling」通常盤", online: nil, user_id: 1, image: nil, used: ""},
  {title: "BANGER NIGHT", artist: "Hey! Say! JUMP", writer: "", composer: "", published: "", record: "Album「SENSE or LOVE」", online: nil, user_id: 1, image: nil, used: ""},
  {title: "Max Beat", artist: "二宮飛鳥, 大和亜季, 鷹富士茄子, 松永涼, 高垣楓", writer: "", composer: "", published: "", record: "2019.05.22 Release「THE IDOLM@STER CINDERELLA GIRLS LITTLE STARS! Max Beat」", online: nil, user_id: 1, image: nil, used: "なし"},
  {title: "Anemone Star", artist: "渋谷凛(CV: 福原綾香)", writer: "", composer: "", published: "", record: "2016.03.30 Release「THE IDOLM@STER CINDERELLA GIRLS STARLIGHT MASTER 01 Snow Wings」", online: nil, user_id: 1, image: nil, used: "なし"},
  {title: "JAPONICA STYLE", artist: "SixTONES", writer: "", composer: "", published: "なし", record: "2nd Single「NAVIGATOR」限定盤", online: nil, user_id: 1, image: nil, used: ""},
  {title: "Fire Bird", artist: "朝香果林(CV: 久保田未夢)", writer: "", composer: "", published: "", record: "2020.09.02 Release 3rd Album", online: nil, user_id: 1, image: nil, used: ""},
  {title: "真夏は誰のモノ？", artist: "黒澤ダイヤ & 黒澤ルビィ", writer: "", composer: "", published: "", record: "「ラブライブ！サンシャイン!! デュオトリオコレクションCD Vol.1 SUMMER VACATION」", online: nil, user_id: 1, image: nil, used: ""},
  {title: "Believe", artist: "嵐", writer: "", composer: "", published: "", record: "", online: nil, user_id: 1, image: nil, used: ""},
  {title: "ワイルド アット ハート", artist: "嵐", writer: "", composer: "", published: "各配信サイト（Apple Music, Spotify, LINE MUSIC etc...）", record: "", online: nil, user_id: 1, image: nil, used: "ラッキーセブン主題歌"},
  {title: "Touch me Now", artist: "櫻井翔", writer: "", composer: "", published: "なし", record: "DVD「SUMMER CONCERT 2003 How's it going?」", online: nil, user_id: 1, image: nil, used: "なし"},
  {title: "so so so", artist: "大野智", writer: "", composer: "", published: "なし", record: "DVD「SUMMER CONCERT 2003 How's it going?」", online: nil, user_id: 1, image: nil, used: ""},
  {title: "La Familia", artist: "松本潤", writer: "", composer: "", published: "なし", record: "DVD「2004 嵐！ いざッNow Tour！！」", online: nil, user_id: 1, image: nil, used: ""},
  {title: "また今日と同じ明日が来る", artist: "二宮和也", writer: "", composer: "", published: "なし", record: "嵐 Album「Are You Happy?」", online: nil, user_id: 1, image: nil, used: ""},
  {title: "Tell me what you wanna be?", artist: "松本潤", writer: "", composer: "", published: "なし", record: "DVD「ARASHI AROUND ASIA Thailand-Taiwan-Korea」「ARASHI AROUND ASIA +in Dome」「ARASHI AROUND ASIA 2008 in TOKYO」収録", online: nil, user_id: 1, image: "l_e_others_501.png", used: "なし"},
  {title: "Secret Daybreak", artist: "デア・アウローラ（新田美波, 速水奏）", writer: "", composer: "", published: "", record: "「STARLIGHT MASTER for the NEXT! 04 Secret Daybreak」", online: nil, user_id: 1, image: nil, used: "なし"},
  {title: "White X'mas", artist: "KAT-TUN", writer: "", composer: "", published: "なし", record: "Single「White X'mas」", online: nil, user_id: 1, image: nil, used: ""}
])

Tag.create!([
  {tag: "クール", user_id: 1},
  {tag: " 3音サビ", user_id: 1},
  {tag: "バラード", user_id: 1},
  {tag: "声加工", user_id: 1},
  {tag: "EDM", user_id: 1},
  {tag: "カルメン調", user_id: 1},
  {tag: "ダンサブル", user_id: 1},
  {tag: "応援系", user_id: 1},
  {tag: "大サビで半音上がる", user_id: 1},
  {tag: "バンド系", user_id: 1},
  {tag: "早口", user_id: 1},
  {tag: "かわいい", user_id: 1},
  {tag: "サビ前に数音", user_id: 1},
  {tag: "ラブソング", user_id: 1},
  {tag: "失恋ソング", user_id: 1},
  {tag: "片思い", user_id: 1},
  {tag: "悲劇的", user_id: 1},
  {tag: "雨に打たれながら聴きたい", user_id: 1},
  {tag: "和風", user_id: 1},
  {tag: "英語歌詞大半", user_id: 1},
  {tag: "ラップ詞有", user_id: 1},
  {tag: "パーティ", user_id: 1},
  {tag: "サーカス", user_id: 1},
  {tag: "奇怪的", user_id: 1},
  {tag: "小悪魔", user_id: 1},
  {tag: "ハモリ", user_id: 1},
  {tag: "アラブ風", user_id: 1},
  {tag: "アンコールに聴きたい", user_id: 1},
  {tag: "不協和音", user_id: 1},
  {tag: "アゲアゲ", user_id: 1},
  {tag: "サビに歌詞がほぼない", user_id: 1},
  {tag: "パラパラ", user_id: 1},
  {tag: "サビから始まる", user_id: 1},
  {tag: "ハロウィン", user_id: 1},
  {tag: "サマーソング", user_id: 1},
  {tag: "ウィンターソング", user_id: 1},
  {tag: "クリスマスソング", user_id: 1},
  {tag: "秋ソング", user_id: 1},
  {tag: "春ソング", user_id: 1},
  {tag: "卒業ソング", user_id: 1},
  {tag: "新生活", user_id: 1},
  {tag: "夏祭り", user_id: 1},
  {tag: "ミュージカル", user_id: 1},
  {tag: "台詞有り", user_id: 1},
  {tag: "奇数音繰り返し", user_id: 1},
  {tag: "明るい", user_id: 1},
  {tag: "男子目線失恋", user_id: 1},
  {tag: "女子目線失恋", user_id: 1},
  {tag: "男子目線ラブソング", user_id: 1},
  {tag: "女子目線ラブソング", user_id: 1},
  {tag: "デュエット", user_id: 1},
  {tag: "感謝ソング", user_id: 1},
  {tag: "大サビ前半静か", user_id: 1},
  {tag: "ヤンデレ", user_id: 1},
  {tag: "舞踏会", user_id: 1},
  {tag: "セクシー", user_id: 1},
  {tag: "特撮っぽい", user_id: 1},
  {tag: "厨二", user_id: 1},
  {tag: "コール＆レスポンス(C&R)", user_id: 1},
  {tag: "甲子園で聴きたい", user_id: 1},
  {tag: "フィナーレ", user_id: 1},
  {tag: "おふざけソング", user_id: 1},
  {tag: "重低音", user_id: 1},
  {tag: "一週間頑張れそう", user_id: 1},
  {tag: "イントロが長め", user_id: 1},
  {tag: "英語詞", user_id: 1},
  {tag: "ボカロとコラボ", user_id: 1},
  {tag: "コーラス", user_id: 1},
  {tag: "ボーカル以外パート有り", user_id: 1},
  {tag: "ギターえぐい", user_id: 1},
  {tag: "ベースメイン", user_id: 1},
  {tag: "特効", user_id: 1},
  {tag: "ハモリが綺麗", user_id: 1},
  {tag: "晴れに聴きたい", user_id: 1},
  {tag: "マーチング", user_id: 1},
  {tag: "猫", user_id: 1},
  {tag: "メロディーの音符が短い", user_id: 1},
  {tag: "メロディーの音符が長い", user_id: 1},
  {tag: "夜に聴きたい", user_id: 1},
  {tag: "曲調変化", user_id: 1},
  {tag: "バイオリン", user_id: 1},
  {tag: "歌わない歌詞有り", user_id: 1},
  {tag: "音の上下が階段状", user_id: 1},
  {tag: "音の上下がほぼない", user_id: 1},
  {tag: "音の上下が激しい", user_id: 1},
  {tag: "妖艶", user_id: 1},
  {tag: "人魚", user_id: 1},
  {tag: "記念ソング", user_id: 1},
  {tag: "メッセージソング", user_id: 1},
  {tag: "ボーカルメイン", user_id: 1},
  {tag: "ワル", user_id: 1},
  {tag: "ボイパ", user_id: 1},
  {tag: "重唱", user_id: 1},
  {tag: "大人ソング", user_id: 1}
])

Like.create!([
  {tweet_id: 7, user_id: 1},
  {tweet_id: 9, user_id: 3},
  {tweet_id: 17, user_id: 3},
  {tweet_id: 17, user_id: 1},
  {tweet_id: 18, user_id: 1},
  {tweet_id: 14, user_id: 1}
])
